Initial work on demo10 (#243)

diff --git a/examples/check_json b/examples/check_json
--- a/examples/check_json
+++ b/examples/check_json
@@ -34,6 +34,12 @@ time ../bin/galsim_json json/demo7.json || exit
 time ../bin/demo8 || exit
 time ../bin/galsim_json json/demo8a.json json/demo8b.json || exit
 
+time ../bin/demo9 || echo "Sorry, sciPy required for running demo9"
+time ../bin/galsim_json demo9.json || echo "Sorry, sciPy required for running demo9"
+
+time ../bin/demo10 || exit
+time ../bin/galsim_json demo10.json || exit
+
 echo 'Checking diffs: (No output means success)'
 
 # demo1:
@@ -72,8 +78,11 @@ for dir_num in {1..4}
 do
     for file_num in {1..5}
     do
-        file_name=mass$dir_num/cluster0$file_num.fits
+        file_name=nfw$dir_num/cluster000$file_num.fits
 	diff output/$file_name output_json/$file_name
     done
 done
+
+# demo10:
+diff output/power_spectrum.fits output_json/power_spectrum.fits 
 
diff --git a/examples/check_yaml b/examples/check_yaml
--- a/examples/check_yaml
+++ b/examples/check_yaml
@@ -34,8 +34,11 @@ time ../bin/galsim_yaml demo7.yaml || exit
 time ../bin/demo8 || exit
 time ../bin/galsim_yaml demo8.yaml || exit
 
-time ../bin/demo9 || exit
-time ../bin/galsim_yaml demo9.yaml || exit
+time ../bin/demo9 || echo "Sorry, sciPy required for running demo9"
+time ../bin/galsim_yaml demo9.yaml || echo "Sorry, sciPy required for running demo9"
+
+time ../bin/demo10 || exit
+time ../bin/galsim_yaml demo10.yaml || exit
 
 echo 'Checking diffs: (No output means success)'
 
@@ -79,4 +82,7 @@ do
 	diff output/$file_name output_yaml/$file_name
     done
 done
+
+# demo10:
+diff output/power_spectrum.fits output_yaml/power_spectrum.fits 
 
