Remove py2.7 and 3.6 from ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,7 +19,7 @@ jobs:
             matrix:
                 # First all python versions in basic linux
                 os: [ ubuntu-latest ]
-                py: [ 2.7, 3.6, 3.7, 3.8, 3.9 ]
+                py: [ 3.7, 3.8, 3.9 ]
                 CC: [ gcc ]
                 CXX: [ g++ ]
 
@@ -97,10 +97,8 @@ jobs:
                 # it gets downloaded and installed properly if it isn't installed.
                 if ${{ matrix.py != 3.7 }}; then sudo -H apt install -y libeigen3-dev; fi
 
-                # Only need this for the mpeg tests, which we don't do on 2.7
-                # Travis needed libav-tools, but that doesn't exist on GHA's system.
-                # GHA needs ffmpeg instead.
-                if ${{ matrix.py > 3.5 }}; then sudo -H apt install -y ffmpeg; fi
+                # Need this for the mpeg tests
+                sudo -H apt install -y ffmpeg
 
             - name: Install fftw, etc. on MacOS
               if: matrix.os == 'macos-latest'
@@ -113,13 +111,19 @@ jobs:
               run: |
                 echo ${{ matrix.os }}
                 # brew update takes forever to run.  Hopefully won't need to enable this too often.
+                # Note: The || true bit here is because brew returns an error code if everything is
+                #       already installed, which is goofy.  So || true means these always give
+                #       non-error values.  If there really is an error, we should notice later
+                #       when trying to use whatever package failed to install.
                 #brew update || true
                 brew install fftw wget || true
                 brew upgrade wget || true
                 brew link --overwrite fftw gcc wget || true
-                if ${{ matrix.py != 3.7 }}; then brew install eigen || true; brew link --overwrite eigen || true; fi
+                brew install eigen || true
+                brew link --overwrite eigen || true
                 brew cask install gfortran || true
-                if ${{ matrix.py > 3.5 }}; then brew install libav || true; brew link --overwrite libav || true; fi
+                brew install libav || true
+                brew link --overwrite libav || true
 
             - name: Download des_data
               run: |
@@ -143,10 +147,6 @@ jobs:
                 # Extra packages needed for testing
                 pip install -U -r test_requirements.txt
                 pip install -U nose codecov coverage
-
-            - name: Install a few extra for python >= 3.7
-              if: matrix.py >= 3.7
-              run: |
                 pip install -U pandas starlink-pyast matplotlib astroplan
 
             - name: List all installed packages for reference
@@ -156,7 +156,7 @@ jobs:
               run: pip install -vvv .
 
             - name: Check download_cosmos only if it changed. (And only on 1 runner)
-              if: matrix.py == 3.6 && github.base_ref != ''
+              if: matrix.py == 3.7 && github.base_ref != ''
               run: |
                 git status
                 git --no-pager log --graph --pretty=oneline --abbrev-commit | head -50
